import { useParams, useNavigate } from 'react-router-dom'
import { Copy, FileDown, Github, RotateCcw, Share2, Monitor, Eye } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { EmptyState } from '@/components/ui/EmptyState'
import { SeverityBadge } from '@/components/shared/SeverityBadge'
import { StatusBadge } from '@/components/shared/StatusBadge'
import { ConfidenceIndicator } from '@/components/shared/ConfidenceIndicator'
import { getBugById } from '@/data/mock-data'
import { formatDateTime, formatRelativeTime } from '@/lib/utils'
import { useAppStore } from '@/stores/app-store'

function buildMarkdownReport(bug: NonNullable<ReturnType<typeof getBugById>>): string {
  return `# ${bug.displayId}: ${bug.title}

**Severity:** ${bug.severity.toUpperCase()}  **Status:** ${bug.status}  **Confidence:** ${bug.confidence}%
**URL:** ${bug.url}

## Description
${bug.description}

## Steps to Reproduce
${bug.stepsToReproduce.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Expected Behavior
${bug.expectedBehavior}

## Actual Behavior
${bug.actualBehavior}

## Root Cause
${bug.rootCause}

## Suggested Resolution
${bug.suggestedResolution}

## Developer Fix
\`\`\`
${bug.developerFix}
\`\`\`

## Regression Test
\`\`\`
${bug.regressionTest}
\`\`\`

## Impact
${bug.impact}

---
Generated by BugPilot AI · Reproduced ${bug.reproductionSuccesses}/${bug.reproductionAttempts} times
`
}

export function BugDetailPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const showToast = useAppStore((s) => s.showToast)
  const bug = getBugById(id ?? '')

  if (!bug) {
    return <EmptyState title="Bug not found" description="This bug may have been removed or resolved." />
  }

  async function handleCopyReport() {
    const markdown = buildMarkdownReport(bug!)
    try {
      await navigator.clipboard.writeText(markdown)
      showToast({ title: 'Report copied', description: 'Markdown bug report copied to clipboard.', variant: 'success' })
    } catch {
      showToast({ title: 'Copy failed', description: 'Your browser blocked clipboard access.', variant: 'error' })
    }
  }

  return (
    <div className="grid gap-6 lg:grid-cols-3">
      <div className="space-y-6 lg:col-span-2">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-mono text-sm text-muted-foreground">{bug.displayId}</span>
            <SeverityBadge severity={bug.severity} />
            <StatusBadge status={bug.status} />
            <ConfidenceIndicator confidence={bug.confidence} />
          </div>
          <h1 className="mt-2 text-2xl font-bold tracking-tight">{bug.title}</h1>
          <p className="mt-1 text-sm text-muted-foreground">{bug.url}</p>

          <div className="mt-4 flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={handleCopyReport}>
              <Copy className="h-3.5 w-3.5" /> Copy Report
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => showToast({ title: 'Generating PDF', description: 'Your PDF report is being prepared.', variant: 'default' })}
            >
              <FileDown className="h-3.5 w-3.5" /> PDF
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => showToast({ title: 'GitHub issue drafted', description: 'A pre-filled issue is ready to submit.', variant: 'success' })}
            >
              <Github className="h-3.5 w-3.5" /> GitHub Issue
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => navigate(`/projects/${bug.projectId}/test`)}
            >
              <RotateCcw className="h-3.5 w-3.5" /> Re-test
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={async () => {
                try {
                  await navigator.clipboard.writeText(window.location.href)
                  showToast({ title: 'Link copied', description: 'Share link copied to clipboard.', variant: 'success' })
                } catch {
                  showToast({ title: 'Copy failed', description: 'Your browser blocked clipboard access.', variant: 'error' })
                }
              }}
            >
              <Share2 className="h-3.5 w-3.5" /> Share
            </Button>
          </div>
        </div>

        {bug.impact && (
          <Card className="border-destructive/40">
            <CardHeader>
              <CardTitle className="text-destructive">Impact</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{bug.impact}</p>
            </CardContent>
          </Card>
        )}

        <Card>
          <CardHeader>
            <CardTitle>Description</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">{bug.description}</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Steps to Reproduce</CardTitle>
          </CardHeader>
          <CardContent>
            <ol className="space-y-3">
              {bug.stepsToReproduce.map((step, i) => (
                <li key={i} className="flex gap-3 text-sm">
                  <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                    {i + 1}
                  </span>
                  <span className="text-muted-foreground">{step}</span>
                </li>
              ))}
            </ol>
          </CardContent>
        </Card>

        <div className="grid gap-4 sm:grid-cols-2">
          <Card>
            <CardHeader className="bg-emerald-500/10">
              <CardTitle className="text-emerald-400">Expected</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{bug.expectedBehavior}</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="bg-red-500/10">
              <CardTitle className="text-red-400">Actual</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{bug.actualBehavior}</p>
            </CardContent>
          </Card>
        </div>

        <Card className="border-primary/30">
          <CardHeader>
            <CardTitle>Root Cause</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground">{bug.rootCause}</p>
            <div>
              <h4 className="text-sm font-semibold">Suggested Resolution</h4>
              <p className="mt-1 text-sm text-muted-foreground">{bug.suggestedResolution}</p>
            </div>
            <div>
              <h4 className="text-sm font-semibold">Developer Fix</h4>
              <pre className="mt-1.5 overflow-x-auto rounded-md bg-black/40 p-3 font-mono text-xs text-emerald-300">
                {bug.developerFix}
              </pre>
            </div>
            <div>
              <h4 className="text-sm font-semibold">Regression Test</h4>
              <pre className="mt-1.5 overflow-x-auto rounded-md bg-black/40 p-3 font-mono text-xs text-blue-300">
                {bug.regressionTest}
              </pre>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>AI Analysis</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">{bug.aiAnalysis}</p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Reproduced</span>
              <span className="font-medium">{bug.reproductionSuccesses}/{bug.reproductionAttempts} attempts</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">First seen</span>
              <span className="font-medium">{formatRelativeTime(bug.firstSeenAt)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Last seen</span>
              <span className="font-medium">{formatDateTime(bug.lastSeenAt)}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">Browser</span>
              <span className="flex items-center gap-1 font-medium">
                <Monitor className="h-3.5 w-3.5" /> {bug.browserInfo.browser}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Viewport</span>
              <span className="font-medium">{bug.browserInfo.viewport}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">OS</span>
              <span className="font-medium">{bug.browserInfo.os}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Screenshots</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-2 gap-2">
            {bug.evidence.map((ev) => (
              <div
                key={ev.id}
                className="flex aspect-video flex-col items-center justify-center gap-1 rounded-md border border-border bg-muted/40 text-muted-foreground"
              >
                <Eye className="h-5 w-5" />
                <span className="px-2 text-center text-[10px]">{ev.label}</span>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Console Logs</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-1.5 rounded-md bg-black/50 p-3 font-mono text-xs">
              {bug.consoleLogs.length === 0 && <p className="text-muted-foreground">No console output captured.</p>}
              {bug.consoleLogs.map((log) => (
                <p
                  key={log.id}
                  className={
                    log.level === 'error' ? 'text-red-400' : log.level === 'warn' ? 'text-amber-400' : 'text-slate-300'
                  }
                >
                  [{log.level}] {log.message}
                </p>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Network Logs</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {bug.networkLogs.length === 0 && <p className="text-sm text-muted-foreground">No network activity captured.</p>}
            {bug.networkLogs.map((log) => (
              <div key={log.id} className="flex items-center gap-2 rounded-md border border-border p-2 text-xs">
                <span className="rounded bg-muted px-1.5 py-0.5 font-mono font-medium">{log.method}</span>
                <span className={`font-mono font-semibold ${log.status >= 400 ? 'text-red-400' : 'text-emerald-400'}`}>
                  {log.status}
                </span>
                <span className="truncate flex-1 text-muted-foreground">{log.url}</span>
                <span className="shrink-0 text-muted-foreground">{log.duration}ms</span>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
